//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customerss
    {
        public int CustomerId { get; set; }
        public Nullable<int> PackageId { get; set; }
        public Nullable<int> CityId { get; set; }
        public string FullName { get; set; }
        public string Phone { get; set; }
        public Nullable<bool> Gender { get; set; }
        public string HotelName { get; set; }
        public string CarDetails { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string Package { get; set; }
        public string Departure { get; set; }
        public string Arrival { get; set; }
        public string From { get; set; }
        public string To { get; set; }
        public Nullable<int> TotalCost { get; set; }
    
        public virtual City City1 { get; set; }
        public virtual Package Package1 { get; set; }
    }
}
